[workspace]
resolver = "3"
members = [
    "controller",
    "nodes/types",
    "nodes/pc/control_logic",
    "nodes/pc/controller_rx",
    "nodes/pc/udp_rx_rpi",
    "nodes/pc/udp_tx_rpi",
    "nodes/rpi/bno_sensor",
    "nodes/rpi/udp_rx_pc",
    "nodes/rpi/udp_tx_pc",
    "nodes/rpi/udp_tx_esp",
    "nodes/tests/input",
    "otlp",
    "nodes/tests/otlp_log",
    "nodes/tests/send_command"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false  # 公開しない場合

[workspace.dependencies]
dora-node-api = {default-features = true , version = "0.4.1"}  # Dora の Rust ノード API
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

dotenv = "0.15.0"
eyre = "0.6"
tokio = { version = "1.50.0", features = ["full"] } # async が必要な場合
