[package]
name = "tcp_esp"
version.workspace = true
edition.workspace = true

[dependencies]
dora-node-api ={ workspace = true }  # Dora の Rust ノード API
tracing.workspace = true
tracing-subscriber.workspace = true
eyre.workspace = true
dotenv.workspace = true
tokio.workspace = true

types ={ path = "../../types" }
postcard = { version = "1", features = ["alloc"] }
serde = { version = "1", features = ["derive"] }
heapless = "0.9"
